sonar.projectKey=lumen-argus_lumen-argus
sonar.organization=lumen-argus
sonar.python.version=3.11,3.12,3.13
sonar.sources=lumen_argus
sonar.tests=tests
sonar.exclusions=docs/**,landing.html,benchmark.py
