"""Forward-proxy tool setup — CA, aliases, shell-profile source line, trust.

Dispatches through :class:`lumen_argus_core.forward_proxy.ForwardProxySetupAdapter`;
the concrete implementation lives in ``lumen-argus-agent``. Proxy-only
PyInstaller bundles never import the agent package, so
:func:`_resolve_forward_proxy_adapter` raises
:class:`ForwardProxyUnavailable` instead of crashing with ``ImportError``.
"""

from __future__ import annotations

import logging
import os
from typing import TYPE_CHECKING

from lumen_argus_core.forward_proxy import ALIASES_PATH as _ALIASES_PATH
from lumen_argus_core.setup import env_file as _env_file
from lumen_argus_core.setup._models import SetupChange
from lumen_argus_core.setup._paths import MANAGED_TAG
from lumen_argus_core.setup._prompts import _prompt_yes
from lumen_argus_core.time_utils import now_iso

if TYPE_CHECKING:
    from lumen_argus_core.detect_models import DetectedClient
    from lumen_argus_core.forward_proxy import ForwardProxySetupAdapter

log = logging.getLogger("argus.setup.forward_proxy")

_FORWARD_PROXY_PORT = 9090
_ALIASES_SOURCE_LINE = (
    '[ -f "$HOME/.lumen-argus/forward-proxy-aliases.sh" ] && '
    'source "$HOME/.lumen-argus/forward-proxy-aliases.sh"  %s type=forward-proxy' % MANAGED_TAG
)


def _resolve_forward_proxy_adapter(target: "DetectedClient", dry_run: bool) -> "ForwardProxySetupAdapter":
    """Fetch the registered adapter or raise ``ForwardProxyUnavailable``.

    Surfaces the missing-adapter case (proxy-only PyInstaller bundle)
    with both an operator WARNING and a user-facing stdout pointer to
    the agent CLI. The raise keeps the control flow explicit — callers
    use it to skip the client in ``run_setup``.
    """
    from lumen_argus_core.forward_proxy import ForwardProxyUnavailable, get_adapter

    adapter = get_adapter()
    if adapter is None:
        log.warning(
            "forward-proxy setup unavailable: no adapter registered "
            "(client=%s, dry_run=%s) — invoke via lumen-argus-agent setup",
            target.client_id,
            dry_run,
        )
        print("  Error: forward-proxy setup is owned by lumen-argus-agent.")
        print("  Run: lumen-argus-agent setup %s" % target.client_id)
        raise ForwardProxyUnavailable(
            "forward-proxy setup requires lumen-argus-agent (run 'lumen-argus-agent setup %s')" % target.client_id
        )
    return adapter


def _fp_step_ca(adapter: "ForwardProxySetupAdapter", target: "DetectedClient", dry_run: bool) -> str:
    """Step 1 — ensure CA cert exists. Returns the cert path."""
    ca_cert = adapter.get_ca_cert_path()
    if adapter.ca_exists():
        log.debug("forward-proxy CA already present: %s", ca_cert)
        print("  CA certificate exists: %s" % ca_cert)
        return ca_cert
    if dry_run:
        log.info("forward-proxy CA missing — would generate at %s (dry-run)", ca_cert)
        print("  [dry-run] Would generate CA certificate at %s" % ca_cert)
        return ca_cert
    try:
        adapter.ensure_ca()
    except Exception:
        log.exception("forward-proxy CA generation failed (client=%s)", target.client_id)
        raise
    ca_cert = adapter.get_ca_cert_path()
    log.info("forward-proxy CA generated: %s", ca_cert)
    print("  CA certificate generated: %s" % ca_cert)
    return ca_cert


def _fp_alias_content(target: "DetectedClient") -> tuple[str, str]:
    """Build the shell alias block for ``target``. Returns ``(tool_binary, content)``.

    ``$HOME``-relative path keeps the alias safe to source across machines.
    """
    tool_binary = target.client_id.replace("_cli", "")
    content = (
        "# lumen-argus forward proxy aliases\n"
        "# Auto-generated by lumen-argus-agent setup — do not edit manually\n\n"
        "alias %s='HTTPS_PROXY=http://localhost:%d "
        'NODE_EXTRA_CA_CERTS="$HOME/.lumen-argus/ca/ca-cert.pem" %s\'\n'
        % (tool_binary, _FORWARD_PROXY_PORT, tool_binary)
    )
    return tool_binary, content


def _fp_step_aliases(
    target: "DetectedClient",
    non_interactive: bool,
    dry_run: bool,
) -> SetupChange | None:
    """Step 2 — write the shell alias file. Returns ``SetupChange`` or ``None``."""
    tool_binary, alias_content = _fp_alias_content(target)

    if not non_interactive:
        print()
        if not _prompt_yes("  Step 2/4: Create shell alias for '%s'?" % tool_binary):
            log.info("forward-proxy alias creation declined by user (client=%s)", target.client_id)
            print("  Skipped alias creation.")
            return None

    _write_aliases(alias_content, dry_run)
    log.info(
        "forward-proxy alias written: client=%s tool=%s dry_run=%s",
        target.client_id,
        tool_binary,
        dry_run,
    )
    return SetupChange(
        timestamp=now_iso(),
        client_id=target.client_id,
        method="forward_proxy_aliases",
        file=_ALIASES_PATH,
        detail=alias_content.strip(),
    )


def _fp_step_profile(
    target: "DetectedClient",
    profile_path: str,
    non_interactive: bool,
    dry_run: bool,
) -> SetupChange | None:
    """Step 3 — add the source line to the shell profile."""
    if not profile_path:
        return None

    if not non_interactive:
        print()
        if not _prompt_yes("  Step 3/4: Add source line to %s?" % profile_path):
            log.info(
                "forward-proxy profile source-line declined by user (client=%s profile=%s)",
                target.client_id,
                profile_path,
            )
            return None

    source_change = _add_aliases_source_line(target.client_id, profile_path, dry_run)
    if source_change is not None:
        log.info(
            "forward-proxy source line added: client=%s profile=%s",
            target.client_id,
            profile_path,
        )
    return source_change


def _fp_step_trust(
    adapter: "ForwardProxySetupAdapter",
    target: "DetectedClient",
    ca_cert: str,
    non_interactive: bool,
    dry_run: bool,
) -> None:
    """Step 4 — optionally install CA to the system trust store (interactive only)."""
    if non_interactive:
        # Non-interactive callers (tray app, CI) shouldn't trigger sudo.
        print("  CA cert at %s — install with: sudo lumen-argus-agent forward-proxy install-ca" % ca_cert)
        return
    if dry_run:
        return

    print()
    if adapter.is_ca_trusted():
        log.debug("forward-proxy CA already trusted at system level")
        print("  Step 4/4: CA certificate already trusted at system level.")
        return

    if not _prompt_yes("  Step 4/4: Install CA cert to system trust store? (requires admin)"):
        log.info("forward-proxy CA system install declined by user")
        print("  Skipped. For Node.js tools, the alias already sets NODE_EXTRA_CA_CERTS.")
        return

    try:
        installed = adapter.install_ca_system()
    except Exception:
        log.exception("forward-proxy system CA install raised (client=%s)", target.client_id)
        raise

    if installed:
        log.info("forward-proxy CA installed to system trust store")
        print("  CA certificate installed to system trust store.")
    else:
        log.warning(
            "forward-proxy system CA install returned False — "
            "user must run 'sudo lumen-argus-agent forward-proxy install-ca'"
        )
        print("  CA install failed. Run manually:")
        print("    sudo lumen-argus-agent forward-proxy install-ca")


def _setup_forward_proxy(
    target: "DetectedClient",
    profile_path: str,
    non_interactive: bool,
    dry_run: bool,
) -> list[SetupChange]:
    """Orchestrate forward-proxy setup for a tool that needs TLS interception.

    Note: no ``proxy_url`` parameter — forward-proxy aliases hardcode
    ``http://localhost:%d`` against ``_FORWARD_PROXY_PORT`` because the
    forward proxy is always local (mitmproxy intercepts on this machine).
    """
    changes: list[SetupChange] = []

    print("  This tool requires forward proxy mode (TLS interception via mitmproxy).")
    print("  The forward proxy intercepts HTTPS traffic so lumen-argus can scan it.\n")

    if not non_interactive and not _prompt_yes("  Step 1/4: Set up forward proxy for %s?" % target.display_name):
        log.info("forward-proxy setup declined by user (client=%s)", target.client_id)
        print("  Skipped.")
        return changes

    adapter = _resolve_forward_proxy_adapter(target, dry_run)
    log.info(
        "forward-proxy setup starting: client=%s adapter=%s dry_run=%s",
        target.client_id,
        type(adapter).__name__,
        dry_run,
    )

    ca_cert = _fp_step_ca(adapter, target, dry_run)

    alias_change = _fp_step_aliases(target, non_interactive, dry_run)
    if alias_change is not None:
        changes.append(alias_change)

    profile_change = _fp_step_profile(target, profile_path, non_interactive, dry_run)
    if profile_change is not None:
        changes.append(profile_change)

    _fp_step_trust(adapter, target, ca_cert, non_interactive, dry_run)

    print("\n  To start the forward proxy:")
    print("    lumen-argus-agent relay --forward-proxy-port %d" % _FORWARD_PROXY_PORT)
    print("  Then open a new terminal to use the alias.")

    return changes


def _write_aliases(content: str, dry_run: bool) -> None:
    """Write the forward-proxy aliases file."""
    if dry_run:
        print("  [dry-run] Would write aliases to %s" % _ALIASES_PATH)
        return
    os.makedirs(_env_file._ARGUS_DIR, mode=0o700, exist_ok=True)
    fd = os.open(_ALIASES_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
    print("  Aliases written to %s" % _ALIASES_PATH)


def _add_aliases_source_line(client_id: str, profile_path: str, dry_run: bool) -> SetupChange | None:
    """Add the aliases source line to the shell profile."""
    try:
        profile_content = ""
        if os.path.isfile(profile_path):
            with open(profile_path, "r", encoding="utf-8") as f:
                profile_content = f.read()

        if "forward-proxy-aliases.sh" in profile_content:
            print("  Source line already in %s" % profile_path)
            return None

        if dry_run:
            print("  [dry-run] Would add source line to %s" % profile_path)
        else:
            with open(profile_path, "a", encoding="utf-8") as f:
                f.write("\n%s\n" % _ALIASES_SOURCE_LINE)
            print("  Added source line to %s" % profile_path)

        return SetupChange(
            timestamp=now_iso(),
            client_id=client_id,
            method="shell_profile",
            file=profile_path,
            detail=_ALIASES_SOURCE_LINE,
        )
    except OSError as e:
        log.warning("could not update shell profile: %s", e)
        return None
